---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://github.com/pluhin/argo-flux-34-26.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-ci-cd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./ci-cd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secret
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitorign
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  driftDetection:
    mode: enabled
  values:
    adminUser: admin
    adminPassword: strongpassword
    service:
      type: ClusterIP
    ingress:
      enabled: false
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - grafana.k8s-9.sa
      path: /
      pathType: Prefix
    env:
      GF_SERVER_ROOT_URL: "https://grafana.k8s-9.sa"
      GF_SERVER_DOMAIN: "grafana.k8s-9.sa"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  url: https://grafana.github.io/helm-charts
  interval: 1h
